export const images = {
  banner: require("./banner.png"),
  bannerReact: require("./banner-react.png"),
  icBell: require("./ic-bell.png"),
  icComment: require("./ic-comment.png"),
  icHand: require("./ic-hand.png"),
  icInstaLike: require("./ic-insta-like.png"),
  icIpad: require("./ic-ipad.png"),
  icPersonFeed: require("./ic-person-feed.png"),
  icPerson1: require("./ic-person1.png"),
  icPerson2: require("./ic-person2.png"),
  icPerson3: require("./ic-person3.png"),
  icPerson4: require("./ic-person4.png"),
  icPurple: require("./ic-purple.png"),
  icWorld: require("./ic-world.png"),
  banner1: require("./img-banner1.png"),
  imgLogin: require("./img-login.png"),
  bgMain: require("./bg-main.png"),
  user1: require("./user1.jpg"),
  user2: require("./user2.jpg"),
  user3: require("./user3.jpg"),
  bank: require("./bank.jpg"),

};