const CLOUD_NAME = process.env.CLOUD_NAME;
const CLOUD_KEY_SECRET = process.env.CLOUD_KEY_SECRET;
const CLOUD_KEY_PRESET = process.env.CLOUD_KEY_PRESET;
const CLOUD_FOLDER_UPLOAD = process.env.CLOUD_TAG;
export { CLOUD_KEY_PRESET, CLOUD_KEY_SECRET, CLOUD_NAME, CLOUD_FOLDER_UPLOAD };